### ISSUE TITLE
avc:  denied  { find } for interface=vendor.oppo.hardware.biometrics.fingerprint

### ISSUE THREAD

**Issue by fwg-cag** [phhusson/device_phh_treble#210]
On my Fairphone FP3 logcat reveals regular errors, which I suspect to be the reason for random unresposiveness of the fingerprint sensor:
`E SELinux : avc:  denied  { find } for interface=vendor.oppo.hardware.biometrics.fingerprint::IBiometricsFingerprint sid=u:r:hal_fingerprint_oppo_compat:s0 pid=1210 scontext=u:r:hal_fingerprint_oppo_compat:s0 tcontext=u:object_r:default_android_hwservice:s0 tclass=hwservice_manager permissive=0`

By adding `allow hal_fingerprint_oppo_compat default_android_hwservice:hwservice_manager find;` in sepolicy/hal.te the error vanished and the situation appears to improve. However, I have no idea where to add this in a smart manner - thus I opened an issue rather than a PR.

**Comment by phhusson** [comment]
This isn't an issue, you can safely ignore this.
As you can see it is for Oppo (or Realme) devices.
It's a bit spamy, but I'd rather have this than NOT having it when I need it.
