### ISSUE TITLE
inrw-system, line 391 is a misstyping

### ISSUE THREAD

**Issue by LeOS-GSI** [phhusson/device_phh_treble#323]
in line 391 rw-system Android-12 branch the leading 'x' is missing. I think that's the root cause that the FOD isn't woking on MI A3

389    # Xiaomi MiA3 uses OLED display which works best with this setting
390      if getprop ro.vendor.build.fingerprint | grep -iq \
391         -e iaomi/laurel_sprout;then
392        setprop persist.sys.qcom-brightness -1
393    fi

**Comment by phhusson** [comment]
it's not missing, it's on purpose, feel free to try it yourself:
```
if getprop ro.vendor.build.fingerprint | grep -iq -e iaomi/laurel_sprout;then
echo "phh is right"
fi
```

 And no, if this was broken, it wouldn't break FOD.
